version: '3.8'

services:
  ai-audio-pipeline:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: ai-audio-pipeline
    ports:
      - "5000:5000"
    volumes:
      # Mount for persistent model cache
      - model_cache:/root/.cache/huggingface
      # Mount for temporary audio files
      - ./temp:/app/temp
      # Mount AWS credentials (optional - only if using credentials file)
      - ${HOME}/.aws:/root/.aws:ro
    environment:
      - FLASK_ENV=production
      - PYTHONUNBUFFERED=1
      # AWS credentials (optional - can also use AWS credentials file or IAM roles)
      - AWS_ACCESS_KEY_ID=${AWS_ACCESS_KEY_ID}
      - AWS_SECRET_ACCESS_KEY=${AWS_SECRET_ACCESS_KEY}
      - AWS_REGION=${AWS_REGION:-us-east-1}
    restart: unless-stopped
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:5000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s
    # Optional: Uncomment if you have NVIDIA GPU support
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

volumes:
  model_cache:
    driver: local
